#gems:
#  - jekyll-archives

# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Mephisto's blog
tagline:             '####'
description:         'A technical blog about Linux, programming and stuff'
url:                 http://mephistophilis.github.io
baseurl:             /
paginate:            5
github:
  repo:  https://github.com/mephistophilis

# About/contact
author:
  name:              Mephistophilis 
  url:               https://mephistophilis.github.io
  email:             mephistophilis@gmail.com

# Custom vars
version:             1.0.0

#jekyll-archives:
#  enabled: all 
#  layout: 'archive'
#  permalinks:
#    year: '/:year/'
#    month: '/:year/:month/'
#    day: '/:year/:month/:day/'
#    tag: '/tag/:name/'
#    category: '/category/:name/'
